require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProgrammesController do

  # This should return the minimal set of attributes required to create a valid
  # Programme. As you add validations to Programme, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "channel_id" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProgrammesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all programmes as @programmes" do
      programme = Programme.create! valid_attributes
      get :index, {}, valid_session
      assigns(:programmes).should eq([programme])
    end
  end

  describe "GET show" do
    it "assigns the requested programme as @programme" do
      programme = Programme.create! valid_attributes
      get :show, {:id => programme.to_param}, valid_session
      assigns(:programme).should eq(programme)
    end
  end

  describe "GET new" do
    it "assigns a new programme as @programme" do
      get :new, {}, valid_session
      assigns(:programme).should be_a_new(Programme)
    end
  end

  describe "GET edit" do
    it "assigns the requested programme as @programme" do
      programme = Programme.create! valid_attributes
      get :edit, {:id => programme.to_param}, valid_session
      assigns(:programme).should eq(programme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Programme" do
        expect {
          post :create, {:programme => valid_attributes}, valid_session
        }.to change(Programme, :count).by(1)
      end

      it "assigns a newly created programme as @programme" do
        post :create, {:programme => valid_attributes}, valid_session
        assigns(:programme).should be_a(Programme)
        assigns(:programme).should be_persisted
      end

      it "redirects to the created programme" do
        post :create, {:programme => valid_attributes}, valid_session
        response.should redirect_to(Programme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved programme as @programme" do
        # Trigger the behavior that occurs when invalid params are submitted
        Programme.any_instance.stub(:save).and_return(false)
        post :create, {:programme => { "channel_id" => "invalid value" }}, valid_session
        assigns(:programme).should be_a_new(Programme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Programme.any_instance.stub(:save).and_return(false)
        post :create, {:programme => { "channel_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested programme" do
        programme = Programme.create! valid_attributes
        # Assuming there are no other programmes in the database, this
        # specifies that the Programme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Programme.any_instance.should_receive(:update_attributes).with({ "channel_id" => "MyString" })
        put :update, {:id => programme.to_param, :programme => { "channel_id" => "MyString" }}, valid_session
      end

      it "assigns the requested programme as @programme" do
        programme = Programme.create! valid_attributes
        put :update, {:id => programme.to_param, :programme => valid_attributes}, valid_session
        assigns(:programme).should eq(programme)
      end

      it "redirects to the programme" do
        programme = Programme.create! valid_attributes
        put :update, {:id => programme.to_param, :programme => valid_attributes}, valid_session
        response.should redirect_to(programme)
      end
    end

    describe "with invalid params" do
      it "assigns the programme as @programme" do
        programme = Programme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Programme.any_instance.stub(:save).and_return(false)
        put :update, {:id => programme.to_param, :programme => { "channel_id" => "invalid value" }}, valid_session
        assigns(:programme).should eq(programme)
      end

      it "re-renders the 'edit' template" do
        programme = Programme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Programme.any_instance.stub(:save).and_return(false)
        put :update, {:id => programme.to_param, :programme => { "channel_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested programme" do
      programme = Programme.create! valid_attributes
      expect {
        delete :destroy, {:id => programme.to_param}, valid_session
      }.to change(Programme, :count).by(-1)
    end

    it "redirects to the programmes list" do
      programme = Programme.create! valid_attributes
      delete :destroy, {:id => programme.to_param}, valid_session
      response.should redirect_to(programmes_url)
    end
  end

end
